import type {
  KnowledgeDiscipline,
  KnowledgeLevel,
  KnowledgeResourceKind,
  OfficialKnowledgeResource,
} from './domain'

export const KNOWLEDGE_KIND_LABELS: Record<KnowledgeResourceKind, string> = {
  book: 'Книга / библиотека',
  clinical_guideline: 'Клинические рекомендации',
  instruction: 'Инструкция',
  standard: 'Нормативный документ',
  checklist: 'Практический навык',
  video: 'Обучающее видео',
  article: 'Статья / руководство',
}

export const KNOWLEDGE_DISCIPLINE_LABELS: Record<KnowledgeDiscipline, string> =
  {
    general: 'Общая медицина',
    anatomy: 'Анатомия',
    physiology: 'Физиология',
    pharmacology: 'Фармакология',
    therapy: 'Терапия',
    surgery: 'Хирургия',
    pediatrics: 'Педиатрия',
    nursing: 'Сестринское дело',
    emergency: 'Неотложная помощь',
    accreditation: 'Аккредитация',
  }

export const KNOWLEDGE_LEVEL_LABELS: Record<KnowledgeLevel, string> = {
  all: 'Для всех уровней',
  college: 'Медицинский колледж',
  university: 'Медицинский вуз',
  residency: 'Ординатура и ДПО',
}

/**
 * This starter catalogue intentionally stores metadata and canonical links,
 * not third-party copies. A document may be mirrored inside MedStart only
 * after its redistribution licence has been verified.
 */
export const OFFICIAL_KNOWLEDGE_RESOURCES: OfficialKnowledgeResource[] = [
  {
    id: 'official-femb-library',
    origin: 'official',
    status: 'published',
    title: 'Медицинские книги и учебные материалы ФЭМБ',
    description:
      'Федеральная электронная медицинская библиотека Минздрава России: учебные и справочные пособия, медицинские книги, журналы и научное наследие.',
    kind: 'book',
    discipline: 'general',
    level: 'all',
    author: 'Минздрав России и Сеченовский Университет',
    publicationLabel: 'Государственная электронная библиотека',
    sourceName: 'ФЭМБ',
    sourceUrl: 'https://femb.ru/',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: [
      'медицинские книги',
      'учебные материалы',
      'справочники',
      'библиотека',
    ],
    featured: true,
  },
  {
    id: 'official-clinical-guidelines',
    origin: 'official',
    status: 'published',
    title: 'Рубрикатор клинических рекомендаций',
    description:
      'Действующие клинические рекомендации по профилактике, диагностике, лечению и реабилитации. Перед применением всегда проверяйте текущую редакцию в рубрикаторе.',
    kind: 'clinical_guideline',
    discipline: 'general',
    level: 'residency',
    author: 'Министерство здравоохранения Российской Федерации',
    publicationLabel: 'Актуальная редакция на стороне источника',
    sourceName: 'Минздрав России',
    sourceUrl: 'https://cr.minzdrav.gov.ru/',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: [
      'клинические рекомендации',
      'диагностика',
      'лечение',
      'реабилитация',
    ],
    featured: true,
  },
  {
    id: 'official-grls',
    origin: 'official',
    status: 'published',
    title: 'Инструкции по медицинскому применению лекарств',
    description:
      'Государственный реестр лекарственных средств. Используйте для проверки зарегистрированных препаратов и официальных инструкций по медицинскому применению.',
    kind: 'instruction',
    discipline: 'pharmacology',
    level: 'all',
    author: 'Министерство здравоохранения Российской Федерации',
    publicationLabel: 'Государственный реестр',
    sourceName: 'ГРЛС',
    sourceUrl: 'https://grls.rosminzdrav.ru/grls.aspx',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: ['лекарства', 'инструкция', 'фармакология', 'реестр'],
    featured: true,
  },
  {
    id: 'official-pharmacopoeia-15',
    origin: 'official',
    status: 'published',
    title: 'Государственная фармакопея Российской Федерации',
    description:
      'Официальный свод требований и положений, устанавливающих показатели качества лекарственных средств, фармацевтических субстанций и препаратов.',
    kind: 'book',
    discipline: 'pharmacology',
    level: 'university',
    author: 'Министерство здравоохранения Российской Федерации',
    publicationLabel: 'XV издание',
    sourceName: 'ФЭМБ',
    sourceUrl: 'https://femb.ru/record/pharmacopea15',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: ['фармакопея', 'лекарственные средства', 'фармация', 'качество'],
  },
  {
    id: 'official-minzdrav-documents',
    origin: 'official',
    status: 'published',
    title: 'Банк документов Минздрава России',
    description:
      'Приказы, порядки оказания медицинской помощи, стандарты, методические рекомендации, инструкции и другие официальные документы.',
    kind: 'standard',
    discipline: 'general',
    level: 'all',
    author: 'Министерство здравоохранения Российской Федерации',
    publicationLabel: 'Официальный банк документов',
    sourceName: 'Минздрав России',
    sourceUrl: 'https://minzdrav.gov.ru/documents',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: ['приказы', 'стандарты', 'порядки', 'нормативные документы'],
  },
  {
    id: 'official-fmza-primary',
    origin: 'official',
    status: 'published',
    title: 'Материалы первичной аккредитации',
    description:
      'Официальные оценочные материалы для тестирования, практических навыков в симулированных условиях и ситуационных задач.',
    kind: 'checklist',
    discipline: 'accreditation',
    level: 'university',
    author: 'Методический центр аккредитации специалистов',
    publicationLabel: 'Специалитет и бакалавриат',
    sourceName: 'ФМЗА',
    sourceUrl: 'https://fmza.ru/fund_assessment_means/',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: ['аккредитация', 'тестирование', 'ОСКЭ', 'ситуационные задачи'],
    featured: true,
  },
  {
    id: 'official-fmza-general-medicine-skills',
    origin: 'official',
    status: 'published',
    title: 'Практические навыки: лечебное дело',
    description:
      'Перечень и паспорта станций ОСКЭ для первичной аккредитации по специальности «Лечебное дело», включая базовую СЛР и экстренную помощь.',
    kind: 'checklist',
    discipline: 'accreditation',
    level: 'university',
    author: 'Методический центр аккредитации специалистов',
    publicationLabel: 'Паспорта станций ОСКЭ',
    sourceName: 'ФМЗА',
    sourceUrl:
      'https://fmza.ru/fund_assessment_means/lechebnoe-delo/perechen-prakticheskikh-navykov-umeniy/',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: ['лечебное дело', 'ОСКЭ', 'СЛР', 'экстренная помощь'],
  },
  {
    id: 'official-fmza-college',
    origin: 'official',
    status: 'published',
    title: 'Оценочные материалы для медицинского СПО',
    description:
      'Официальные материалы первичной аккредитации для сестринского, лечебного, акушерского дела, фармации, лабораторной диагностики и других специальностей СПО.',
    kind: 'checklist',
    discipline: 'accreditation',
    level: 'college',
    author: 'Методический центр аккредитации специалистов',
    publicationLabel: 'Среднее профессиональное образование',
    sourceName: 'ФМЗА',
    sourceUrl:
      'https://fmza.ru/srednee-professionalnoe-obrazovanie/spetsialnosti-spo/',
    language: 'ru',
    verifiedAt: '2026-07-26',
    tags: ['СПО', 'сестринское дело', 'аккредитация', 'практические навыки'],
  },
  {
    id: 'official-who-hand-hygiene',
    origin: 'official',
    status: 'published',
    title: 'WHO Guidelines on Hand Hygiene in Health Care',
    description:
      'Руководство Всемирной организации здравоохранения по гигиене рук и профилактике передачи инфекций при оказании медицинской помощи.',
    kind: 'clinical_guideline',
    discipline: 'nursing',
    level: 'all',
    author: 'World Health Organization',
    publicationLabel: 'Руководство ВОЗ',
    sourceName: 'ВОЗ',
    sourceUrl: 'https://www.who.int/publications/i/item/9789241597906',
    language: 'en',
    verifiedAt: '2026-07-26',
    tags: ['гигиена рук', 'инфекционная безопасность', 'ВОЗ', 'профилактика'],
  },
  {
    id: 'official-who-emergency-framework',
    origin: 'official',
    status: 'published',
    title: 'WHO Emergency Care System Framework',
    description:
      'Модель ВОЗ по ключевым функциям экстренной помощи: от места происшествия и транспортировки до приёмного отделения и раннего стационарного этапа.',
    kind: 'article',
    discipline: 'emergency',
    level: 'residency',
    author: 'World Health Organization',
    publicationLabel: 'Руководство ВОЗ',
    sourceName: 'ВОЗ',
    sourceUrl:
      'https://www.who.int/publications/i/item/who-emergency-care-system-framework',
    language: 'en',
    verifiedAt: '2026-07-26',
    tags: ['экстренная помощь', 'неотложная помощь', 'ВОЗ', 'маршрутизация'],
  },
]
