import Link from 'next/link'
import { ArrowRight, BadgeCheck, CalendarDays, MessageCircle, Search } from 'lucide-react'

const features = [
  { title: 'Проверенные репетиторы', text: 'В каталоге публикуются только профили, прошедшие модерацию.', icon: BadgeCheck },
  { title: 'Удобный поиск', text: 'Выбирайте специалиста по предмету, опыту и стоимости занятия.', icon: Search },
  { title: 'Расписание', text: 'Все подтверждённые занятия собраны в личном кабинете.', icon: CalendarDays },
  { title: 'Общение', text: 'Обсуждайте цели и формат занятий напрямую с репетитором.', icon: MessageCircle },
]

export default function HomePage() {
  return <main className="min-h-dvh bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link href="/" className="text-xl font-bold text-violet-700">MedStart</Link><div className="flex items-center gap-3"><Link href="/login" className="rounded-xl px-4 py-2 font-medium text-slate-700">Войти</Link><Link href="/register/student" className="rounded-xl bg-violet-600 px-4 py-2 font-semibold text-white">Регистрация</Link></div></div></header><section className="mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:py-28"><div><span className="inline-flex rounded-full bg-violet-100 px-4 py-2 text-sm font-semibold text-violet-700">Медицинское образование без лишних барьеров</span><h1 className="mt-6 text-5xl font-bold leading-tight text-slate-900">Найдите медицинского репетитора под свою цель</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">MedStart помогает студентам самостоятельно выбирать репетиторов, записываться на занятия и вести обучение в одном кабинете.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register/student" className="inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-6 py-3.5 font-semibold text-white">Начать поиск<ArrowRight className="h-4 w-4" /></Link><Link href="/register/tutor" className="rounded-2xl border border-slate-300 bg-white px-6 py-3.5 font-semibold text-slate-700">Стать репетитором</Link></div></div><div className="rounded-[36px] bg-gradient-to-br from-violet-700 via-violet-600 to-indigo-700 p-8 text-white shadow-2xl"><p className="text-sm text-violet-100">Как это работает</p><ol className="mt-6 space-y-5">{['Создайте студенческий аккаунт','Выберите репетитора в каталоге','Согласуйте время и формат','Начните занятие'].map((item,index)=><li key={item} className="flex items-center gap-4 rounded-2xl bg-white/10 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-white font-bold text-violet-700">{index+1}</span><span className="font-semibold">{item}</span></li>)}</ol></div></section><section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{features.map(({title,text,icon:Icon})=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 text-violet-600"><Icon className="h-6 w-6" /></div><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></section></main>
}
